# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: rick@mcgeer.com
author_name: Rick McGeer
has_binder: false
has_settings: false
kind: frontend
labextension_name: galyleo_extension
project_short_description: A fast test of reading a file and displaying it
python_name: galyleo_extension
repository: n/a
test: false

